version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps
    steps:
      - run:
          command: |
            echo "placeholder for build job"
  preview-build:
    docker:
      - image: circleci/buildpack-deps
    steps:
      - run:
          command: |
            echo "building a preview build named: ${PREVIEW_NAME}"